### ISSUE TITLE
Error running generator

### ISSUE THREAD

**Issue by aleksip** [mortenson/generator-twig-components-webpack#1]
Trying to get this to work, but ran into an error:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-twig-components-webpack/generators/app/templates/base/.gitignore
    at EditionInterface.exports.copy (/usr/lib/node_modules/generator-twig-components-webpack/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
    at module.exports.writing (/usr/lib/node_modules/generator-twig-components-webpack/generators/app/index.js:64:13)
    at Object.<anonymous> (/usr/lib/node_modules/generator-twig-components-webpack/node_modules/yeoman-generator/lib/index.js:399:25)
    at /usr/lib/node_modules/generator-twig-components-webpack/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/lib/node_modules/generator-twig-components-webpack/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/lib/node_modules/generator-twig-components-webpack/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Using node 8.9.4 on Ubuntu 16.04.

**Comment by mortenson** [comment]
It looks like `npm` reads nested package.json files and respects their `files` definition, which is causing most of the template's files to not be published to `npm`. I'm looking into this now.

**Comment by mortenson** [comment]
And there's another bug specifically with .gitignore - it can never be included in published npm packages. 😿 

@aleksip could you try (globally) updating generator-twig-components-webpack to 0.0.9 and re-running the command? Thanks for the report.

**Comment by aleksip** [comment]
Success! 😺 Thank you for the quick response and your very interesting work on Twig and Web Components. 👍

Btw I'm developing on a Vagrant box and had to add `host: '0.0.0.0'` to the `devServer` section in `webpack.config.js` to be able to access the DevServer from my host machine. I don't know if it is a good idea to add it to the config or not, but maybe there could be a note about this in the documentation.

**Comment by mortenson** [comment]
@aleksip From a quick search I can see that a lot of people have had this problem with Webpack's dev server (https://github.com/webpack/webpack-dev-server/issues/147).

I went ahead and added the host config to the app template: https://github.com/mortenson/generator-twig-components-webpack/commit/d6667c5c008a15a0d610bd982dca8b6b813fd9b6, the next release should include this change. Thanks again! Please file more issues as you run into stuff.
